config/routes.rb
Microposts::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  

  resources :users do
	  member do
		  get :following,:followers
	  end
  end
  resources :sessions,only: [:new,:create,:destroy]
  resources :microposts,only: [:create,:destroy]
  resources :relationships,only: [:create,:destroy]
  
  match '/help',to: 'static_pages#help'
  match '/about',to: 'static_pages#about'
  match '/contact',to: 'static_pages#contact'

  match '/signup',to: 'users#new'
  match '/signin',to: 'sessions#new'
  match '/signout',to: 'sessions#destroy',via: :delete

  root to: "static_pages#home"

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			<!--表单包含<%= object.errors.count %>项错误.-->
			表单包含以下错误.
		</div>
		<!--<ul>
			<%= object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>-->
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= will_paginate @feed_items %>
		<%= render partial: 'shared/feed_item',collection: @feed_items %>
		<%= will_paginate @feed_items %>
	<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
<%= link_to gravatar_for(feed_item.user),feed_item.user %>
<span class="user">
	<%= link_to feed_item.user.name,feed_item.user %>
</span>
<span class="content"><%= sanitize(feed_item.content) %></span>
<span class="timestamp">
	发布于 <%= time_ago_in_words(feed_item.created_at) %>前.
</span>
<% if current_user?(feed_item.user) %>
	<%= link_to "删除",feed_item,method: :delete,data: { confirm: "你确定？"},title: feed_item.content %>
<% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages',object: f.object %>
	<div class="field" >
		<%= error_div(@micropost,:content,"微博内容")%>
		<%= f.text_area :content,placeholder: "撰写新微博...",class: "ckeditor" %>
	</div>
	<%= f.submit "发布",class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		关注
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		粉丝
	</a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
	<%= gravatar_for current_user,size: 52 %>
</a>
<h1>
	<%= current_user.name %>
</h1>
<span>
	<%= link_to "查看我的资料",current_user %>
</span>
<span>
	<%= current_user.microposts.count %>条微博
</span>