config/routes.rb
Microposts::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  

  resources :users do
	  member do
		  get :following,:followers
	  end
  end
  resources :sessions,only: [:new,:create,:destroy]
  resources :microposts,only: [:create,:destroy]
  resources :relationships,only: [:create,:destroy]
  
  match '/help',to: 'static_pages#help'
  match '/about',to: 'static_pages#about'
  match '/contact',to: 'static_pages#contact'

  match '/signup',to: 'users#new'
  match '/signin',to: 'sessions#new'
  match '/signout',to: 'sessions#destroy',via: :delete

  root to: "static_pages#home"

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
	Microposts by Sven Liu
</small>
<nav>
<ul>
	<li><%= link_to "关于我们",about_path %></li>
	<li><%= link_to "联系我们",contact_path %></li>
	<li><a href="#">更多动态</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
<div class="navbar-inner">
	<div class="container">
		<%= link_to "我的微博",root_path,id: 'logo' %>
		<nav>
		<ul class="nav pull-right">
			<li><%= link_to "首页",root_path %></li>
			<li><%= link_to "帮助",help_path %></li>
			<% if signed_in? %>
				<li><%= link_to "用户",users_path %></li>
				<li id="fat-menu" class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">帐户 <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to "个人资料",current_user %></li>
						<li><%= link_to "设置",edit_user_path(current_user) %></li>
						<li class="divider"></li>
						<li>
						<%= link_to "登出",signout_path,method: "delete" %>
						</li>
					</ul>
					</li>
				<% else %>
					<li><%= link_to "登录",signin_path %></li>
				<% end %>
		</ul>
		</nav>
	</div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key,value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>

</body>
</html>